
# Git Clients

Git is the underlying version control system used by platforms like GitHub.

The goal of a Git client is to help us track changes in our code, and interface with code hosting platforms like GitHub. Professionals may prefer to use Git from the command line, but there is a learning curve. Instead, beginners are encouraged to get started with GitHub Desktop, which provides an easier to use graphical user interface (GUI).

## GitHub Desktop

### Installation and Configuration

Students are encouraged to install [GitHub Desktop software](https://desktop.github.com/), for Mac or Windows.

After installing, you will need to login with your GitHub account credentials. See this [GitHub Desktop setup guide](https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/setting-up-github-desktop) for more information.

After installing, from the settings, choose VS Code as your default text editor.

### Success Criteria

You should be able to open the GitHub Desktop application, and visit the settings to see you are logged in with your GitHub account.
