project:
  type: book # website
  output-dir: "_build"
  preview:
    port: 4567
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Intro to Open Source and Version Control"
  author: "Michael J Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

#website:

  site-url: https://gw-ospo.github.io/version-control-tutorial
  repo-url: https://github.com/gw-ospo/version-control-tutorial
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  #sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  reader-mode: true

  #cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  logo: images/ospo-logo.png

  #sidebar:
  #  contents:
  #    - index.qmd
  #
  #    - section:
  #      href: prereqs/local-dev-setup/index.qmd
  #      title: "Prerequisites"
  #      contents:
  #        - prereqs/local-dev-setup/github.qmd
  #        - prereqs/local-dev-setup/vs-code-text-editor.qmd
  #        - prereqs/local-dev-setup/terminal.qmd
  #        - prereqs/local-dev-setup/anaconda.qmd
  #        - prereqs/local-dev-setup/git-client.qmd


  chapters:
    - index.qmd

    #- "-------------"

    - part: "Notes"
      chapters:
        - notes/open-source.qmd
        - notes/version-control.qmd





    #- "-------------"

    - part: "Development Tools"
      chapters:
        - dev-tools/github.qmd
        - dev-tools/vs-code-text-editor.qmd
        - href: dev-tools/git-client.qmd
          text: "GitHub Desktop"


    #- "-------------"
    - part: "Exercises"
      chapters:
        - href: exercises/1-version-control-workflow/index.qmd
          text: Version Control Workflow
        - href: exercises/2-pull-request-workflow/index.qmd
          text: Pull Request Workflow
        - href: exercises/3-developer-team-workflow/index.qmd
          text: Dev Team Workflow
        - href: exercises/4-open-source-workflow/index.qmd
          text: Open Source Workflow




    - "-------------"
    - about.qmd
    - "-------------"


  appendices:
    - part: "Command-line Tools"
      chapters:
      - href: dev-tools/clis/brew.qmd
        text: "Homebrew (Mac OS)"
      - dev-tools/clis/git.qmd

  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  page-footer:
    center: |
      <p>&copy; Copyright 2025, <a href="https://michael-rossetti.org/">Michael J Rossetti</a>.
        Originally created for the <a href="https://ospo.gwu.edu/">GWU Open Source Program Office (OSPO)</a>.
        Licensed under <a href="http://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>.
      </p>




#bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 6
    toc-expand: true # keep all levels visible
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: solar # vapor # superhero # slate # solar #quartz # darkly
      #dark: [superhero, superhero-gw-dark-theme.scss]
    css: styles.css
    number-sections: false
    from: markdown+emoji # enable emojis




  #pdf:
  #  documentclass: scrreprt
