
:::{.content-hidden when-format="html" when-page="index"}
# Open Source Collaboration and Version Control Tutorial
:::

<p style="font-size:20px;">
Demystify the version control process, and learn how to collaborate on coding projects with other researchers and developers.
</p>





## Overview

This tutorial begins by introducing key concepts and motivations behind version control, highlighting its value in research and software development.

Next, the tutorial guides you through installing and configuring beginner-friendly tools to get started with version control.

Finally, the tutorial provides hands-on exercises with step-by-step instructions and walkthrough videos to help you practice essential version control workflows, including team collaboration and contributing to open source projects.

## Learning Objectives

1. Discuss open source software.
2. Discuss the importance of version control in software and research development projects.
3. Set up a GitHub repository for version control purposes.
4. Use GitHub Desktop software to manage the code staging and committing process, and to interface with a remote repository on GitHub.
5. Practice a version controlled development workflow.
5. Employ Git branching strategies to manage different versions of code.
6. Collaborate with peers by pulling and merging changes from a shared repository.


## Additional Resources

Official GitHub Docs:

  + <https://docs.github.com/en>
  + <https://docs.github.com/en/get-started/using-github/github-flow>
  + <https://githubtraining.github.io/training-manual>
  + <https://training.github.com/downloads/github-git-cheat-sheet.pdf>
